### ISSUE TITLE
need code refactoring

### ISSUE THREAD

**Issue by neizod** [neizod/open-sky#3]
right now every `.js` files is just a mess, anyone up for refactoring them?

**Comment by evandroabukamel** [comment]
Can I help? What do you need exactly? Geez, this code is a really mess.

**Comment by ebarnsli** [comment]
nightmare

**Comment by evandroabukamel** [comment]
I made a small PR that fixes minor errors. https://github.com/neizod/open-sky/pull/4
Need some time or explanation to understand the whole project to contribute more.

**Comment by osmarpetry** [comment]
@evandroabukamel I included prettier script in the package.json, to run your prettier from CLI 

My PR is there, with the eslint rules done: https://github.com/neizod/open-sky/pull/5

**Comment by evandroabukamel** [comment]
@osmarpetry , surely this will help to make the code clearer. Thanks.

**Comment by neizod** [comment]
@evandroabukamel this code dated back to the day I start programming ... with JS as my 2nd language! So yes you can expect it to be a nightmare. What I think right now is to update it to be acceptable by nowaday JS standard.

**Comment by evandroabukamel** [comment]
@neizod , the project is really nice, I liked it. I will try to help when I can, little by little.

**Comment by evandroabukamel** [comment]
I've created a branch where I'm refactoring controller script.
https://github.com/evandroabukamel/open-sky/tree/%40evandroabukamel/refactor-controller

**Comment by osmarpetry** [comment]
@neizod you can accept our two PR? They are already done
